name: alh_pdf_view_example
description: "Demonstrates how to use the alh_pdf_view plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.2

  alh_pdf_view:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  stream_transform: ^2.1.0

dependency_overrides:
  alh_pdf_view_android:
    path: ../../alh_pdf_view_android
  alh_pdf_view_ios:
    path: ../../alh_pdf_view_ios
  alh_pdf_view_platform_interface:
    path: ../../alh_pdf_view_platform_interface

flutter:
  uses-material-design: true
  assets:
    - assets/sampleWithLink.pdf
    - assets/sample.pdf
