# This is a basic workflow to help you get started with Actions
name: Flutter Test, Format, Analyze

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'

      - name: Get Flutter version
        run: flutter --version

      - name: Go to alh_pdf_view
        run: cd alh_pdf_view

      - name: Check alh_pdf_view
        run: |
          flutter pub get &&
          dart format --output=none --set-exit-if-changed . &&
          flutter analyze &&
          flutter test

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'

      - name: Get Flutter version
        run: flutter --version

      - name: Go to alh_pdf_view
        run: cd alh_pdf_view

      - name: Check alh_pdf_view
        uses: .check_project

      - name: Go to alh_pdf_view_ios
        run: |
          cd ..
          cd alh_pdf_view_ios
          *check_project

      - name: Go to alh_pdf_view_android
        run: |
          cd ..
          cd alh_pdf_view_android
          *check_project

      - name: Go to alh_pdf_view_platform_interface
        run: |
          cd ..
          cd alh_pdf_view_platform_interface
          *check_project
